name: flutter_ble
description: A comprehensive Flutter plugin for interacting with Bluetooth Low Energy (BLE) devices.
version: 0.3.0
homepage: https://github.com/Toglefritz/flutter_ble

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.splendidendeavors.flutter_ble
        pluginClass: FlutterBlePlugin
      ios:
        pluginClass: FlutterBlePlugin
      macos:
        pluginClass: FlutterBlePlugin