name: scan_example
description: Demonstrates how to scan for nearby BLE devices using the FlutterSplendidBLE plugin.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Provides localized string values
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  # Plugin for interacting with BLE devices.
  flutter_splendid_ble: ^0.4.2
  # Provides a cross-platform (iOS, Android) API to request and check permissions
  permission_handler: ^10.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/